site_name: hospitalco
site_description: Providing a simple, focussed marketplace for healthcare.
repo_url: https://github.com/hospitalCo/hopitalco-backend
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/hospitalCo">hospitalCo</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
