# Generated by Django 3.0.3 on 2020-03-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
