# Generated by Django 3.0.3 on 2020-03-28 10:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200328_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='items',
        ),
        migrations.AddField(
            model_name='requirement',
            name='fullfilled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='market.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.Category'),
            preserve_default=False,
        ),
    ]
